AWSTemplateFormatVersion: '2010-09-09'
Description: Create boilerplate, stand-alone EFS with imported VPC
Resources:
 
  MyEFSFileSystemResource:
    Type: 'AWS::EFS::FileSystem'
    Properties:
      PerformanceMode: generalPurpose
      Encrypted: true
      FileSystemPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "elasticfilesystem:ClientMount"
            Principal:
            
              AWS: "*"

  MyEFSMountTargetResource1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref MyEFSFileSystemResource
      SubnetId: !ImportValue "MyVPC-priv-sub-a"
      SecurityGroups:
        - !ImportValue "MyVPC-sg"

  MyEFSMountTargetResource2:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref MyEFSFileSystemResource
      SubnetId: !ImportValue "MyVPC-priv-sub-b"
      SecurityGroups:
        - !ImportValue "MyVPC-sg"

  MyEFSAccessPointResource:
    Type: 'AWS::EFS::AccessPoint'
    Properties:
      FileSystemId: !Ref MyEFSFileSystemResource
      PosixUser:
        Uid: "1000"
        Gid: "1000"
      RootDirectory:
        CreationInfo:
          OwnerGid: "1000"
          OwnerUid: "1000"
          Permissions: "0777"
        Path: "/"

Outputs:
  efsFileSystemResource:
    Description: EFS File System ID
    Value: !Ref MyEFSFileSystemResource
    Export:
      Name: !Join ["-", [!Ref "AWS::StackName", "file-system"]]
  efsAccessPointResource:
    Description: EFS Access Point ID
    Value: !Ref MyEFSAccessPointResource
    Export:
      Name: !Join ["-", [!Ref "AWS::StackName", "access-point"]]      